--retirar caract do pacientes(prof, est civil e sexo) e plugar direto na fato como uma outra dimensao
--atualizar primeiro as dimensoes depois a fato
--ETL extract transf load

CREATE DATABASE TCC

--CONSTRUÇÃO DAS TABELAS
CREATE TABLE F_CONSULTAS(
ID_CONSULTA INT NOT NULL,
ID_PACIENTE INT NOT NULL,
ID_DENTISTA INT NOT NULL,
ID_CONVENIO INT NOT NULL,
ID_SERVICO INT NOT NULL,
ID_TRATAMENTO INT NOT NULL,
DT_CONSULTA DATETIME NOT NULL,
VALOR_CONSULTA INT NOT NULL
)

CREATE TABLE D_PACIENTES(
ID_PACIENTE INT IDENTITY(1,1) NOT NULL,
NM_PAC VARCHAR(30),
PROFISSAO VARCHAR(50),
EST_CIVIL VARCHAR(20),
EMAIL VARCHAR(40),
INDICACAO VARCHAR(20),
CEP VARCHAR(9),
FONE VARCHAR(11)
)

CREATE TABLE D_DENTISTAS(
ID_DENTISTA INT IDENTITY(1,1) NOT NULL,
CRO INT,
EMAIL_DENT VARCHAR(50)
)

CREATE TABLE D_CONVENIO(
ID_CONVENIO INT IDENTITY(1,1) NOT NULL,
NUM_CARTEIRA INT,
NM_CONV VARCHAR(50)
)

CREATE TABLE D_SERVICOS(
ID_SERVICO INT IDENTITY(1,1) NOT NULL,
DS_SERV VARCHAR(100),
)

CREATE TABLE D_TRATAMENTOS(
ID_TRATAMENTO INT IDENTITY(1,1) NOT NULL,
DS_TRAT VARCHAR(100),
DT_INIC_TRAT DATETIME,
DT_FIM_TRAT DATETIME
)

--PKs
ALTER TABLE F_CONSULTAS
ADD CONSTRAINT PK_CONSULTA PRIMARY KEY(ID_CONSULTA)

ALTER TABLE D_PACIENTES
ADD CONSTRAINT PK_PACIENTE PRIMARY KEY(ID_PACIENTE)

ALTER TABLE D_DENTISTAS
ADD CONSTRAINT PK_DENTISTA PRIMARY KEY(ID_DENTISTA)

ALTER TABLE D_CONVENIO
ADD CONSTRAINT PK_CONVENIO PRIMARY KEY(ID_CONVENIO)

ALTER TABLE D_SERVICOS
ADD CONSTRAINT PK_SERVICO PRIMARY KEY(ID_SERVICO)

ALTER TABLE D_TRATAMENTOS
ADD CONSTRAINT PK_TRATAMENTO PRIMARY KEY(ID_TRATAMENTO)

--FKs
ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES D_PACIENTES (ID_PACIENTE)

ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_DENTISTA FOREIGN KEY (ID_DENTISTA) REFERENCES D_DENTISTAS (ID_DENTISTA)

ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES D_CONVENIO (ID_CONVENIO)

ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_SERVICO FOREIGN KEY (ID_SERVICO) REFERENCES D_SERVICOS (ID_SERVICO)

ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_TRATAMENTO FOREIGN KEY (ID_TRATAMENTO) REFERENCES D_TRATAMENTOS (ID_TRATAMENTO)

ALTER TABLE D_PACIENTES
ADD NUM_CARTEIRA INT

ALTER TABLE D_CONVENIO
DROP COLUMN NUM_CARTEIRA

ALTER TABLE D_SERVICOS
ADD VALOR_CONSULTA INT

ALTER TABLE D_SERVICOS
ADD DT_CONSULTA DATETIME

ALTER TABLE F_CONSULTAS 
DROP CONSTRAINT FK_TRATAMENTO

ALTER TABLE F_CONSULTAS 
DROP COLUMN DT_CONSULTA

ALTER TABLE F_CONSULTAS 
DROP COLUMN VALOR_CONSULTA

DROP TABLE D_TRATAMENTOS

ALTER TABLE D_SERVICOS
ADD ID_DENTISTAS INT NOT NULL

ALTER TABLE D_SERVICOS
ADD ID_PACIENTES INT NOT NULL

ALTER TABLE D_SERVICOS
ADD CONSTRAINT FK_DENTISTAS FOREIGN KEY (ID_DENTISTA) REFERENCES D_DENTISTAS (ID_DENTISTA)

ALTER TABLE D_SERVICOS
ADD CONSTRAINT FK_DENTISTAS FOREIGN KEY (ID_DENTISTA) REFERENCES D_DENTISTAS (ID_DENTISTA)

ALTER TABLE D_SERVICOS
ALTER COLUMN VALOR DECIMAL(10,2)

-- GERANDO MASSA DE DADOS

INSERT INTO D_CONVENIO VALUES ('AMIL DENTAL')
INSERT INTO D_PACIENTES(NM_PAC,NUM_CARTEIRA) VALUES('DANIELA DE SOUZA M DA SILVA',874505070)
INSERT INTO D_DENTISTAS(CRO,EMAIL_DENT) VALUES(27537,'CONSULTORIO_DRA.SUZY@HOTMAIL.COM')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RADIOGRAFIA PERIAPICAL',5.2,'20180221')

INSERT INTO D_CONVENIO VALUES ('AMIL DENTAL')
INSERT INTO D_PACIENTES(NM_PAC,NUM_CARTEIRA) VALUES('CLAUDINA DOS SANTOS DO ROSARIO',071688521)
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('EXODONTIA DE RAIZ RESIDUAL',31.41,'20180403')

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('CONSULTA ODONTOLOGIA',19.34,'20180403')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180403')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180403')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180403')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180403')

INSERT INTO D_PACIENTES(NM_PAC,NUM_CARTEIRA) VALUES('LARISSA MORAES ALCANTARA',981240550)

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RADIOGRAFIA PERIAPICAL',5.2,'20180430')

INSERT INTO D_PACIENTES(NM_PAC,NUM_CARTEIRA) VALUES('RENAN LEANDRO DE ROSSI',452681235)

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('CONSULTA ODONTOLOGICA',8.98,'20180404')

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',14.97,'20180502')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',14.97,'20180502')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',14.97,'20180502')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',14.97,'20180502')

INSERT INTO D_PACIENTES(NM_PAC,NUM_CARTEIRA) VALUES('SARAH DE JESUS MENDES',062599550)

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('CONSULTA ODONTOLOGICA',19.34,'20171219')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180430')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180430')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180430')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180430')

INSERT INTO D_PACIENTES(NM_PAC,NUM_CARTEIRA) VALUES('VANESSA PEDROSO DE ALCANTARA',868888796)

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RESTAURACAO EM RESINA',31.89,'20180317')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RESTAURACAO EM RESINA',31.89,'20180317')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RESTAURACAO EM RESINA',28.21,'20180328')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RESTAURACAO EM RESINA',28.21,'20180328')

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180430')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180430')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180430')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180430')

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('EXODONTIA SIMPLES DE DECIDUO',19.98,'20180112')

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('CONSULTA ODONTOLOGICA',8.98,'20180404')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',14.97,'20180502')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',14.97,'20180502')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',14.97,'20180502')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',14.97,'20180502')

INSERT INTO D_PACIENTES(NM_PAC,NUM_CARTEIRA) VALUES('ISABELA SANTOS AVILA',072648374)

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('EXODONTIA DE RAIZ RESIDUAL',31.41,'20180519')

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('CONSULTA ODONTOLOGICA',19.34,'20180504')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180507')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180507')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180507')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',12.31,'20180507')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RESTAURACAO EM RESINA',31.89,'20180504')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RADIOGRAFIA PERIAPICAL',5.2,'20180507')

INSERT INTO D_PACIENTES(NM_PAC,NUM_CARTEIRA) VALUES('SAMUEL VIEIRA OLIVEIRA',072252486)

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RADIOGRAFIA PERIAPICAL',5.2,'20180602')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('RADIOGRAFIA PERIAPICAL',5.2,'20180602')

INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('CONSULTA ODONTOLOGICA',19.34,'20180315')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',11.13,'20180517')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',11.13,'20180517')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',11.13,'20180517')
INSERT INTO D_SERVICOS(DS_SERV,VALOR,DATA_REALIZ) VALUES('LIMPEZA',11.13,'20180517')

SELECT DS_SERV,SUM(VALOR) FROM D_SERVICOS
GROUP BY DS_SERV



