/*
CREATE DATABASE TCC

--CONSTRUÇÃO DAS TABELAS
CREATE TABLE F_CONSULTAS(
ID_CONSULTA INT NOT NULL,
ID_PACIENTE INT NOT NULL,
ID_DENTISTA INT NOT NULL,
ID_CONVENIO INT NOT NULL,
ID_SERVICO INT NOT NULL,
ID_TRATAMENTO INT NOT NULL,
DT_CONSULTA DATETIME NOT NULL,
VALOR_CONSULTA INT NOT NULL
)

CREATE TABLE D_PACIENTES(
ID_PACIENTE INT IDENTITY(1,1) NOT NULL,
NM_PAC VARCHAR(30),
PROFISSAO VARCHAR(50),
EST_CIVIL VARCHAR(20),
EMAIL VARCHAR(40),
INDICACAO VARCHAR(20),
CEP VARCHAR(9),
FONE VARCHAR(11)
)

CREATE TABLE D_DENTISTAS(
ID_DENTISTA INT IDENTITY(1,1) NOT NULL,
CRO INT,
EMAIL_DENT VARCHAR(50)
)

CREATE TABLE D_CONVENIO(
ID_CONVENIO INT IDENTITY(1,1) NOT NULL,
NUM_CARTEIRA INT,
NM_CONV VARCHAR(50)
)

CREATE TABLE D_SERVICOS(
ID_SERVICO INT IDENTITY(1,1) NOT NULL,
DS_SERV VARCHAR(100),
)

CREATE TABLE D_TRATAMENTOS(
ID_TRATAMENTO INT IDENTITY(1,1) NOT NULL,
DS_TRAT VARCHAR(100),
DT_INIC_TRAT DATETIME,
DT_FIM_TRAT DATETIME
)

--PKs
ALTER TABLE F_CONSULTAS
ADD CONSTRAINT PK_CONSULTA PRIMARY KEY(ID_CONSULTA)

ALTER TABLE D_PACIENTES
ADD CONSTRAINT PK_PACIENTE PRIMARY KEY(ID_PACIENTE)

ALTER TABLE D_DENTISTAS
ADD CONSTRAINT PK_DENTISTA PRIMARY KEY(ID_DENTISTA)

ALTER TABLE D_CONVENIO
ADD CONSTRAINT PK_CONVENIO PRIMARY KEY(ID_CONVENIO)

ALTER TABLE D_SERVICOS
ADD CONSTRAINT PK_SERVICO PRIMARY KEY(ID_SERVICO)

ALTER TABLE D_TRATAMENTOS
ADD CONSTRAINT PK_TRATAMENTO PRIMARY KEY(ID_TRATAMENTO)

--FKs
ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES D_PACIENTES (ID_PACIENTE)

ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_DENTISTA FOREIGN KEY (ID_DENTISTA) REFERENCES D_DENTISTAS (ID_DENTISTA)

ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES D_CONVENIO (ID_CONVENIO)

ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_SERVICO FOREIGN KEY (ID_SERVICO) REFERENCES D_SERVICOS (ID_SERVICO)

ALTER TABLE F_CONSULTAS
ADD CONSTRAINT FK_TRATAMENTO FOREIGN KEY (ID_TRATAMENTO) REFERENCES D_TRATAMENTOS (ID_TRATAMENTO)
*/

--INSERT INTO VALUES 